#### Specific definitions for linux

APACHE_CFLAGS = -I/usr/local/apache/include
MYSQL_CFLAGS = -I/usr/local/include/mysql

CFLAGS = -O3 -fomit-frame-pointer -fno-defer-pop -I/usr/local/include -fPIC
LDFLAGS = -L/usr/local/lib
LIBDL = -ldl
LIBGC = -lgc
LIBM = -lm
LIBZ = -lz
LIBNEKO = -lneko
LIBPCRE = -lpcre
MAKESO = gcc -shared -WBsymbolic -fPIC

LIBMYSQL_STATIC = /usr/local/lib/mysql/libmysqlclient.a
LIBMYSQL_DYNAMIC = -lmysql
LIBMYSQL = ${LIBZ} ${LIBMYSQL_STATIC}
