/*

	In order to link with older MSVCRT.DLL, it might be necessary to add
	a few additional functions that are generated by MSVC

*/
long _ftol( double f );
long _ftol2( double f) { return _ftol(f); };

