parameters:
  name: 'BuildLinux'
  vmImage: 'ubuntu-20.04'
  linkType: 'static'
  arch: 'amd64'

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 0
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - script: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'
        displayName: Install Earthly
      - script: |
          sudo apt-get install qemu binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker stop earthly-buildkitd || true
        displayName: Install QEMU
      - script: earthly --platform=linux/${{ parameters.arch }} +package --LINK_TYPE=${{ parameters.linkType }}
        displayName: Build package
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: ${{ parameters.name }}Binaries
          targetPath: bin/${{ parameters.linkType }}/linux/${{ parameters.arch }}/neko-$(NEKO_VERSION)-linux64.tar.gz
